<?php
/**
 * Custom Sitemap Template.
 *
 * Outputs XML sitemap content for custom taxonomy-based sitemaps.
 * Handles index, year, month, and day sitemap generation based on granularity.
 *
 * @package XWP\CustomXmlSitemap
 */

namespace XWP\CustomXmlSitemap;

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Get query variables.
$sitemap_type  = get_query_var( Sitemap_Router::QUERY_VAR_SITEMAP );
$sitemap_year  = get_query_var( Sitemap_Router::QUERY_VAR_YEAR );
$sitemap_month = get_query_var( Sitemap_Router::QUERY_VAR_MONTH );
$sitemap_day   = get_query_var( Sitemap_Router::QUERY_VAR_DAY );

// Validate sitemap type.
if ( empty( $sitemap_type ) ) {
	status_header( 404 );
	nocache_headers();
	exit;
}

// Look up the sitemap post by slug.
$sitemap_post = Sitemap_CPT::get_sitemap_by_slug( $sitemap_type );

if ( ! $sitemap_post ) {
	status_header( 404 );
	nocache_headers();
	exit;
}

// Create generator instance.
$generator = new Sitemap_Generator( $sitemap_post );

// Get sitemap XML (from cache or generate).
// XML is cached in post meta for fast retrieval.
// The generator handles granularity logic internally.
if ( ! empty( $sitemap_day ) && ! empty( $sitemap_month ) && ! empty( $sitemap_year ) ) {
	// Day sitemap: /sitemaps/{type}/{year}-{month}-{day}.xml.
	$xml = $generator->get_day_sitemap( (int) $sitemap_year, (int) $sitemap_month, (int) $sitemap_day );
} elseif ( ! empty( $sitemap_month ) && ! empty( $sitemap_year ) ) {
	// Month sitemap: /sitemaps/{type}/{year}-{month}.xml.
	$xml = $generator->get_month_sitemap( (int) $sitemap_year, (int) $sitemap_month );
} elseif ( ! empty( $sitemap_year ) ) {
	// Year sitemap: /sitemaps/{type}/{year}.xml.
	$xml = $generator->get_year_sitemap( (int) $sitemap_year );
} else {
	// Index sitemap: /sitemaps/{type}/index.xml.
	$xml = $generator->get_index();
}

// Set XML headers.
header( 'Content-Type: application/xml; charset=UTF-8' );
header( 'X-Robots-Tag: noindex, follow' );

// Output XML content.
// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- XML is generated by Sitemap_Generator with proper escaping.
echo $xml;

exit;
